---

- name: Installing zabbix agent rpm package
  get_url:
    url: http://repo.zabbix.com/zabbix/{{ version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ version }}-1+trusty_all.deb
    dest: /tmp/
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"

- name: Installing zabbix server rpm package
  get_url: 
    url: http://repo.zabbix.com/zabbix/{{ version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ version }}-1+xenial_all.deb
    dest: /tmp/
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial" 

- name: dpkg packages...
  command: dpkg -i /tmp/zabbix-release_{{ version }}-1+trusty_all.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "trusty"

- name: dpkg packages
  command: dpkg -i /tmp/zabbix-release_{{ version }}-1+xenial_all.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial"

- name: Update the cache...
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installing Zabbix Agent ...
  apt: name=zabbix-agent state=installed
  when: ansible_os_family == "Debian"

- name: Installing Zabbix Agent ...
  yum: name=zabbix-agent state=installed
  when: ansible_os_family == "Redhat"

- name: Verify if HostMetadata already defined ...
  shell: grep -ri HostMetadata= /etc/zabbix/zabbix_agentd.conf | cut -d'=' -f2
  register: data

- name: Configuring Zabbix Agent ...
  template: src=zabbix_agent.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644
  when: data.stdout == ""
  notify: zabbix-agent restart

- name: Appending HostMetadata value ...
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    replace: 'HostMetadata=\1,{{ zabbix_host_metadata }}'
    regexp: 'HostMetadata=(.*)'
  when: data.stdout != ""


- name: Fetch monitoring tag
  include: nginx.yml
  when:
    - zabbix_host_metadata == "nginx"

- name: Fetch monitoring tag
  include: redis.yml
  when:
    - zabbix_host_metadata == "redis"
